export const hikesData = [
  {
    id: 1,
    name: "Thompson River Viewpoint & Juniper Bluff Trail",
    location: "Juniper Beach",
    day: 1,
    distance: "2 km",
    difficulty: "Easy",
    duration: "30 min",
    elevationGain: "50m",
    description:
      "A short evening hike with beautiful views of the Thompson River. Perfect for sunset views after setting up camp.",
    status: "confirmed",
    imageUrl: "/images/hikes/thompson-river-viewpoint-juniper-bluff-trail.png",
    trailLink: "https://www.alltrails.com/",
  },
  {
    id: 2,
    name: "Gibraltar Rock & Paul Lake Loop",
    location: "Near Kamloops",
    day: 2,
    distance: "5 km",
    difficulty: "Moderate",
    duration: "2 hrs",
    elevationGain: "150m",
    description:
      "Morning hike before continuing to Revelstoke. Features panoramic views of Paul Lake and surrounding mountains.",
    status: "confirmed",
    imageUrl: "/images/hikes/gibraltar-rock-paul-lake-loop.png",
    trailLink: "https://www.alltrails.com/",
  },
  {
    id: 3,
    name: "Johnston Canyon Trail",
    location: "Banff",
    day: 4,
    distance: "5.1 km",
    difficulty: "Easy-Moderate",
    duration: "2 hrs",
    elevationGain: "120m",
    description:
      "A beautiful trail through Johnston Canyon with views of waterfalls. Features steel catwalks fixed to the canyon walls.",
    status: "confirmed",
    imageUrl: "/images/hikes/johnston-canyon-trail.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/ab/banff/activ/randonee-hiking/johnston",
  },
  {
    id: 4,
    name: "Lake Agnes Tea House",
    location: "Banff",
    day: 5,
    distance: "7.4 km",
    difficulty: "Moderate",
    duration: "3 hrs",
    elevationGain: "385m",
    description:
      "Scenic hike to the historic Lake Agnes Tea House with mountain views. The tea house has been serving tea since 1905.",
    status: "confirmed",
    imageUrl: "/images/hikes/lake-agnes-tea-house.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/ab/banff/activ/randonee-hiking/lakelouise",
  },
  {
    id: 5,
    name: "Tunnel Mountain",
    location: "Banff",
    day: 5,
    distance: "4.3 km",
    difficulty: "Easy",
    duration: "1.5 hrs",
    elevationGain: "260m",
    description:
      "Optional afternoon hike with panoramic views of Banff. One of the most popular short hikes in Banff with great views of the town and Bow Valley.",
    status: "optional",
    imageUrl: "/images/hikes/tunnel-mountain.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/ab/banff/activ/randonee-hiking/banff",
  },
  {
    id: 6,
    name: "Bow Falls Viewpoint",
    location: "Banff",
    day: 5,
    distance: "0.5 km",
    difficulty: "Easy",
    duration: "15 min",
    elevationGain: "10m",
    description: "Short walk to view the impressive Bow Falls. Located near the Fairmont Banff Springs Hotel.",
    status: "optional",
    imageUrl: "/images/hikes/bow-falls-viewpoint.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/ab/banff/activ/randonee-hiking/banff",
  },
  {
    id: 7,
    name: "Emerald Lake Loop (Yoho NP)",
    location: "Yoho National Park",
    day: 6,
    distance: "5.2 km",
    difficulty: "Easy",
    duration: "1.5 hrs",
    elevationGain: "Minimal",
    description:
      "Beautiful loop around the stunning Emerald Lake in Yoho National Park. The vibrant turquoise water is surrounded by mountains.",
    status: "confirmed",
    imageUrl: "/images/hikes/emerald-lake-loop.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/bc/yoho/activ/randonnee-hike",
  },
  {
    id: 8,
    name: "Golden Rotary Trail",
    location: "Golden",
    day: 6,
    distance: "7 km",
    difficulty: "Easy",
    duration: "2 hrs",
    elevationGain: "Minimal",
    description:
      "Pleasant trail along the river in Golden. Great for spotting local wildlife and enjoying river views.",
    status: "confirmed",
    imageUrl: "/images/hikes/golden-rotary-trail.png",
    trailLink: "https://www.alltrails.com/",
  },
  {
    id: 9,
    name: "Inspiration Woods Trail",
    location: "Revelstoke",
    day: 7,
    distance: "2.5 km",
    difficulty: "Easy",
    duration: "1 hr",
    elevationGain: "80m",
    description: "Morning hike through beautiful forest before departing Revelstoke. Features old-growth cedar trees.",
    status: "confirmed",
    imageUrl: "/images/hikes/inspiration-woods-trail.png",
    trailLink: "https://www.alltrails.com/",
  },
  {
    id: 10,
    name: "Knox Mountain Park",
    location: "Kelowna",
    day: 8,
    distance: "Various loops",
    difficulty: "Easy-Moderate",
    duration: "1-2 hrs",
    elevationGain: "Up to 300m",
    description:
      "Various hiking options with views of Okanagan Lake and Kelowna. The Apex Trail to the summit offers the best views.",
    status: "confirmed",
    imageUrl: "/images/hikes/knox-mountain-park.png",
    trailLink: "https://www.kelowna.ca/parks-recreation/parks/knox-mountain-park",
  },
  {
    id: 11,
    name: "Joffre Lakes Trail",
    location: "Between Pemberton and Lillooet",
    day: 9,
    distance: "10 km",
    difficulty: "Moderate",
    duration: "4 hrs",
    elevationGain: "400m",
    description:
      "Optional add-on hike en route to Vancouver with stunning turquoise lakes. Features three beautiful glacier-fed lakes with increasing elevation.",
    status: "optional",
    imageUrl: "/images/hikes/joffre-lakes-trail.png",
    trailLink: "https://bcparks.ca/explore/parkpgs/joffre_lks/",
  },
  {
    id: 12,
    name: "Sunshine Meadows",
    location: "Banff",
    day: 5,
    distance: "Various trails",
    difficulty: "Easy-Moderate",
    duration: "2-4 hrs",
    elevationGain: "Varies",
    description:
      "Accessible via gondola (seasonal), these alpine meadows offer spectacular wildflower displays in summer and stunning mountain views.",
    status: "optional",
    imageUrl: "/images/hikes/sunshine-meadows.png",
    trailLink: "https://www.pc.gc.ca/en/pn-np/ab/banff/activ/randonee-hiking/sunshine",
  },
]
