export const packingData = {
  clothing: {
    name: "Clothing",
    items: [
      { name: "T-shirts", quantity: 5 },
      { name: "Long-sleeve shirts", quantity: 3 },
      { name: "Hiking pants", quantity: 2 },
      { name: "Shorts", quantity: 2 },
      { name: "Underwear", quantity: 9 },
      { name: "Socks", quantity: 9 },
      { name: "Hiking socks", quantity: 4 },
      { name: "Fleece jacket", quantity: 1 },
      { name: "Rain jacket", quantity: 1 },
      { name: "Down/insulated jacket", quantity: 1 },
      { name: "Hiking boots", quantity: 1 },
      { name: "Casual shoes", quantity: 1 },
      { name: "Sandals", quantity: 1 },
      { name: "Swimwear", quantity: 1 },
      { name: "Hat with brim", quantity: 1 },
      { name: "Beanie/warm hat", quantity: 1 },
      { name: "Gloves", quantity: 1 },
      { name: "Sleepwear", quantity: 2 },
    ],
  },
  hiking: {
    name: "Hiking Gear",
    items: [
      { name: "Daypack", quantity: 1 },
      { name: "Hiking poles", quantity: 2 },
      { name: "Water bottles/hydration system", quantity: 2 },
      { name: "Headlamp", quantity: 1 },
      { name: "First aid kit", quantity: 1 },
      { name: "Blister treatment", quantity: 1 },
      { name: "Sunglasses", quantity: 1 },
      { name: "Sunscreen", quantity: 1 },
      { name: "Insect repellent", quantity: 1 },
      { name: "Trail map/guidebook", quantity: 1 },
      { name: "GPS device or app", quantity: 1 },
      { name: "Whistle", quantity: 1 },
      { name: "Pocket knife", quantity: 1 },
      { name: "Binoculars", quantity: 1 },
      { name: "Camera", quantity: 1 },
      { name: "Extra batteries/power bank", quantity: 1 },
      { name: "Snacks/energy bars", quantity: 10 },
    ],
  },
  camping: {
    name: "Camping",
    items: [
      { name: "Tent", quantity: 1 },
      { name: "Sleeping bags", quantity: 2 },
      { name: "Sleeping pads", quantity: 2 },
      { name: "Pillows", quantity: 2 },
      { name: "Camping chairs", quantity: 2 },
      { name: "Headlamps/flashlights", quantity: 2 },
      { name: "Lantern", quantity: 1 },
      { name: "Cooking stove", quantity: 1 },
      { name: "Fuel", quantity: 1 },
      { name: "Cookware", quantity: 1 },
      { name: "Plates/bowls", quantity: 2 },
      { name: "Utensils", quantity: 2 },
      { name: "Mugs/cups", quantity: 2 },
      { name: "Cooler", quantity: 1 },
      { name: "Water container", quantity: 1 },
      { name: "Trash bags", quantity: 5 },
      { name: "Matches/lighter", quantity: 2 },
      { name: "Multi-tool", quantity: 1 },
      { name: "Duct tape", quantity: 1 },
      { name: "Rope/cord", quantity: 1 },
    ],
  },
  toiletries: {
    name: "Toiletries",
    items: [
      { name: "Toothbrush", quantity: 2 },
      { name: "Toothpaste", quantity: 1 },
      { name: "Floss", quantity: 1 },
      { name: "Shampoo/conditioner", quantity: 1 },
      { name: "Soap/body wash", quantity: 1 },
      { name: "Deodorant", quantity: 2 },
      { name: "Towel", quantity: 2 },
      { name: "Washcloth", quantity: 2 },
      { name: "Razor", quantity: 2 },
      { name: "Lip balm with SPF", quantity: 2 },
      { name: "Medications", quantity: 1 },
      { name: "Hand sanitizer", quantity: 1 },
      { name: "Wet wipes", quantity: 1 },
      { name: "Toilet paper", quantity: 1 },
      { name: "Feminine products", quantity: 1 },
    ],
  },
  electronics: {
    name: "Electronics",
    items: [
      { name: "Smartphones", quantity: 2 },
      { name: "Phone chargers", quantity: 2 },
      { name: "Camera", quantity: 1 },
      { name: "Camera charger/extra batteries", quantity: 1 },
      { name: "Power bank", quantity: 1 },
      { name: "Headphones", quantity: 2 },
      { name: "Tablet/e-reader", quantity: 1 },
      { name: "Car charger", quantity: 1 },
      { name: "Travel adapter", quantity: 1 },
    ],
  },
  documents: {
    name: "Documents",
    items: [
      { name: "Driver's license", quantity: 2 },
      { name: "Health insurance cards", quantity: 2 },
      { name: "Credit/debit cards", quantity: 4 },
      { name: "Cash", quantity: 1 },
      { name: "Campsite reservation confirmation", quantity: 1 },
      { name: "Hotel reservation confirmation", quantity: 1 },
      { name: "National Park pass", quantity: 1 },
      { name: "Emergency contact information", quantity: 1 },
      { name: "Road map", quantity: 1 },
    ],
  },
}
