export const tripData = [
  {
    day: 1,
    date: "May 3, 2025",
    title: "Vancouver → Juniper Beach",
    from: "Vancouver",
    to: "Juniper Beach",
    departureTime: "8:00 AM",
    driveTime: "~3 hours",
    distance: 337,
    accommodation: "Campsite 24, Juniper Beach Provincial Park",
    accommodationType: "camping",
    accommodationDetails: "Reservation #BCIN26-1113826B1",
    hikes: [
      {
        name: "Thompson River Viewpoint & Juniper Bluff Trail",
        distance: "2 km",
        difficulty: "Easy",
        duration: "30 min",
        description: "A short evening hike with beautiful views of the Thompson River.",
      },
    ],
    notes:
      "Alternative: Drive 20 min to Cache Creek for Dinner at Rancher's Cookhouse & Heritage Trail stroll. Night Activity: Campfire & stargazing.",
  },
  {
    day: 2,
    date: "May 4, 2025",
    title: "Juniper Beach → Revelstoke",
    from: "Juniper Beach",
    to: "Revelstoke",
    departureTime: "8:00 AM",
    driveTime: "3.5-4 hours",
    distance: 350,
    accommodation: "Airbnb in Revelstoke",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Gibraltar Rock & Paul Lake Loop",
        distance: "5 km",
        difficulty: "Moderate",
        duration: "2 hrs",
        description: "Morning hike before continuing to Revelstoke.",
      },
    ],
    notes:
      "Evening: Explore downtown Revelstoke. Alternative accommodation options: Snowforest Campground or Blanket Creek Provincial Park.",
  },
  {
    day: 3,
    date: "May 5, 2025",
    title: "Revelstoke → Banff + Calgary Evening",
    from: "Revelstoke",
    to: "Banff",
    departureTime: "9:00 AM",
    driveTime: "~3.5 hours",
    distance: 280,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    accommodationDetails: "Check-in: May 5-7",
    hikes: [],
    notes:
      "Afternoon: Quick Bow Falls visit or Cascade Gardens stroll. Drive to Calgary: Leave Banff ~5 PM (90 km, 1 hr 15 min). Meeting: Dinner & French lesson with Karla's instructor in Calgary (~7 PM). Return: Drive back to Moxy Banff (arrive ~10 PM).",
  },
  {
    day: 4,
    date: "May 6, 2025",
    title: "Full Banff Exploration",
    from: "Banff",
    to: "Banff",
    departureTime: "9:00 AM",
    driveTime: "N/A",
    distance: 0,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Johnston Canyon Trail",
        distance: "5.1 km",
        difficulty: "Easy-Moderate",
        duration: "2 hrs",
        description: "A beautiful trail through Johnston Canyon with views of waterfalls.",
      },
    ],
    notes:
      "Midday: Lunch in Banff town. Afternoon: Banff Gondola & Summit Walk (Sulphur Mountain). Optional Side-Trip: Cave & Basin National Historic Site.",
  },
  {
    day: 5,
    date: "May 7, 2025",
    title: "More Banff Hikes",
    from: "Banff",
    to: "Banff",
    departureTime: "8:00 AM",
    driveTime: "N/A",
    distance: 0,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Lake Agnes Tea House",
        distance: "7.4 km",
        difficulty: "Moderate",
        duration: "3 hrs",
        description: "Scenic hike to the historic Lake Agnes Tea House with mountain views.",
      },
      {
        name: "Tunnel Mountain",
        distance: "4.3 km",
        difficulty: "Easy",
        duration: "1.5 hrs",
        description: "Optional afternoon hike with panoramic views of Banff.",
      },
      {
        name: "Bow Falls Viewpoint",
        distance: "0.5 km",
        difficulty: "Easy",
        duration: "15 min",
        description: "Short walk to view the impressive Bow Falls.",
      },
    ],
    notes: "Choose 1-2 afternoon options. Sunshine Meadows (via gondola) is also available seasonally.",
  },
  {
    day: 6,
    date: "May 8, 2025",
    title: "Banff → Revelstoke via Golden",
    from: "Banff",
    to: "Revelstoke",
    departureTime: "8:00 AM",
    driveTime: "~4 hours",
    distance: 350,
    accommodation: "Airbnb in Revelstoke",
    accommodationType: "hotel",
    accommodationDetails: "Alternative: Repeat camp at Snowforest or Blanket Creek",
    hikes: [
      {
        name: "Emerald Lake Loop (Yoho NP)",
        distance: "5.2 km",
        difficulty: "Easy",
        duration: "1.5 hrs",
        description: "Beautiful loop around the stunning Emerald Lake in Yoho National Park.",
      },
      {
        name: "Golden Rotary Trail",
        distance: "7 km",
        difficulty: "Easy",
        duration: "2 hrs",
        description: "Pleasant trail along the river in Golden.",
      },
    ],
    notes: "Travel via Trans-Canada Highway with stops in Yoho National Park and Golden.",
  },
  {
    day: 7,
    date: "May 9, 2025",
    title: "Revelstoke → Kelowna",
    from: "Revelstoke",
    to: "Kelowna",
    departureTime: "10:00 AM",
    driveTime: "~4 hours",
    distance: 395,
    accommodation: "Cousin Elaine's Home in Kelowna",
    accommodationType: "family",
    hikes: [
      {
        name: "Inspiration Woods Trail",
        distance: "2.5 km",
        difficulty: "Easy",
        duration: "1 hr",
        description: "Morning hike through beautiful forest before departing Revelstoke.",
      },
    ],
    notes: "Family stay with cousin Elaine in Kelowna.",
  },
  {
    day: 8,
    date: "May 10, 2025",
    title: "Kelowna Adventures",
    from: "Kelowna",
    to: "Kelowna",
    departureTime: "9:00 AM",
    driveTime: "N/A",
    distance: 0,
    accommodation: "Cousin Elaine's Home in Kelowna",
    accommodationType: "family",
    hikes: [
      {
        name: "Knox Mountain Park",
        distance: "Various loops",
        difficulty: "Easy-Moderate",
        duration: "1-2 hrs",
        description: "Various hiking options with views of Okanagan Lake and Kelowna.",
      },
    ],
    notes: "Afternoon: Winery tour or Okanagan Lake stroll.",
  },
  {
    day: 9,
    date: "May 11, 2025",
    title: "Kelowna → Vancouver",
    from: "Kelowna",
    to: "Vancouver",
    departureTime: "9:00 AM",
    driveTime: "~4 hours",
    distance: 410,
    accommodation: "",
    accommodationType: "",
    hikes: [
      {
        name: "Joffre Lakes Trail",
        distance: "10 km",
        difficulty: "Moderate",
        duration: "4 hrs",
        description: "Optional add-on hike en route to Vancouver with stunning turquoise lakes.",
      },
    ],
    notes: "Optional Add-On: Joffre Lakes Trail en route back to Vancouver.",
  },
]
